### ISSUE TITLE
RemoteObjects does not work after upgraded to Version 84.0.486.0 (Official build) canary (64-bit)

### ISSUE THREAD

**Issue by momo-coco-yin** [MicrosoftEdge/WebViewFeedback#158]
Hi there, 

After upgraded to Version 84.0.486.0 (Official build) canary (64-bit) today, the remoteObjects does not work in the sample code. 

Uncaught (in promise) TypeError: Cannot read property 'sample' of undefined
    at HTMLButtonElement.<anonymous> (ScenarioAddRemoteObject.html:48)
(anonymous) @ ScenarioAddRemoteObject.html:48

Do I need to reset something after upgraded to a new version? thanks.

**Comment by pontusn** [comment]
We also experience problems with remote objects for 84.0.486.0

**Comment by david-risney** [comment]
Thank you for reporting this issue! I will take a look.

The issue you mentioned about webview just being totally broken from the start should be fixed in the latest canary builds of Edge.

**Comment by pontusn** [comment]
Tested 84.0.488.0 (Canary) now:
- Remote objects is still not working
- Two of four panes that hosts WebView2 fails with 0x80007139F and NULL as arguments to callback when creating host. 

Did not have time to check Dev-channel.
