### ISSUE TITLE
32-bit WebView2Loader.dll is copied when using 64-bit .NET program

### ISSUE THREAD

**Issue by antti-j** [MicrosoftEdge/WebViewFeedback#182]
I run into issue with 64-bit .NET program when trying to use Microsoft.Web.WebView2. 32-bit WebView2Loader.dll is copied to Output Path. WebView2 doesn't work in this case. Workaround is to add some post build event to copy 64-bit WebView2Loader.dll from packages\Microsoft.Web.WebView2.0.9.515-prerelease\build\x64 to Output Path. 

Could the nuget package fixed somehow to do this automatically?

I don't really know why this old .NET program is 64-bit. And does it really need to be. I can reproduce this issue also by setting Platform Target to x64
![image](https://user-images.githubusercontent.com/54351950/82221301-7cd07800-9928-11ea-9649-5f73b71ecb79.png)

**Comment by david-risney** [comment]
Great issue, thanks for reporting! We'll look into it. Hopefully this is just an issue in our nuget that we can fix.

**Comment by briangdd** [comment]
I'm getting the same bug, but adding this post build step cures it as described above:
xcopy /E /I /Y %userprofile%\.nuget\packages\microsoft.web.webview2\0.9.515-prerelease\build\x64\WebView2Loader.dll $(TargetDir).

Obviously the path will change at some point though.

![image](https://user-images.githubusercontent.com/5197247/82357354-e621bb00-99fc-11ea-9659-b128f1154a01.png)

**Comment by dianaqu** [comment]
@antti-j Hi, I am tying to look into the issue. But I can't repo, would you mind sharing your csproj file config a bit?

**Comment by mikerossman** [comment]
I can confirm the bug related to x64 builds under VS 2019 16.5.4.  Also confirmed the manual xcopy post build step fixes the problem. The designer code that adds the control to the form's Controls collection is what throws the exception. Screenshot of the exception and broken project attached. 


![Webview2 NullReferenceException](https://user-images.githubusercontent.com/22735384/84970578-fb1b6800-b0e8-11ea-9d5d-b3164ff3e622.JPG)

[BrokenProject.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/4795932/BrokenProject.zip)

**Comment by douglas-jordan** [comment]
Same problem occurs in C++ builds, the DLL filename is the same for 32 or 64 bit.

**Comment by dianaqu** [comment]
@douglas-jordan do you mean for c++, 32bits dlls also got copied to 64bits?

**Comment by douglas-jordan** [comment]
> @douglas-jordan do you mean for c++, 32bits dlls also got copied to 64bits?

Either, 32 copied over 64 or 64 bit copied over 32 bit.  I suppose if I created a separate build folder for the two builds this would not happen, but there is no way to have them both in the same folder at runtime.

**Comment by dianaqu** [comment]
@antti-j @douglas-jordan @briangdd @mikerossman If you don't mind me asking. Which processor is your machine? what platform is your AnyCPU runs on

**Comment by antti-j** [comment]
>  If you don't mind me asking. Which processor is your machine? what platform is your AnyCPU runs on

@dianaqu  Here is the full solution[Webview2Wpf.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/4825077/Webview2Wpf.zip) It is .net framework project.

This happens e.g. in Azure VM with the following processor:
![image](https://user-images.githubusercontent.com/54351950/85549240-74a2e100-b628-11ea-9cfe-241c382f6a34.png)

**Comment by mikerossman** [comment]
AMD FX-8350

**Comment by joergbattermann** [comment]
Well if you look at the imported _Microsoft.Web.WebView2.targets_ file, you'll see the lines below, which are just wrong in those cases where 'Prefer 32bit' is unchecked or, as the issue writer did, the target platform is manually set. The marked condition sets the EffectivePlatform to x86 for Any( )CPU, no matter what and hence copies the x86 _WebView2Loader.dll_ variant.

So this might need some more specific conditions OR allow and explain how one can enforce the 64bit _WebView2Loader.dll_ variant.

![image](https://user-images.githubusercontent.com/828/89451753-fa07ce00-d75c-11ea-9540-c0815ed975bb.png)

**Comment by dianaqu** [comment]
Hi @joergbattermann  Please see my latest comment in this issue: https://github.com/MicrosoftEdge/WebViewFeedback/issues/377.
We are planning on shipping the fix with next SDK release

**Comment by joergbattermann** [comment]
Awesome, thanks @dianaqu! 👍

**Comment by billybooth** [comment]
@dianaqu said:
> Hi @joergbattermann Please see my latest comment in this issue: #377.
> We are planning on shipping the fix with next SDK release

Although a fix for this particular issue in the next release will be great, is there any plan to support "Any CPU" releases without "Prefer 32-bit" checked?  By this, I don't mean a `.targets` fix that copies the 64-bit loader to the output path, but rather the ability to ship both the 32-bit and 64-bit loader and let the WebView2 choose the correct loader at runtime.

Thanks!

**Comment by dianaqu** [comment]
> @dianaqu said:
> 
> > Hi @joergbattermann Please see my latest comment in this issue: #377.
> > We are planning on shipping the fix with next SDK release
> 
> Although a fix for this particular issue in the next release will be great, is there any plan to support "Any CPU" releases without "Prefer 32-bit" checked? By this, I don't mean a `.targets` fix that copies the 64-bit loader to the output path, but rather the ability to ship both the 32-bit and 64-bit loader and let the WebView2 choose the correct loader at runtime.
> 
> Thanks!

Hi @billybooth ,
Sorry if I made the confusion. When I say the issue is fixed, I mean it by we had made changes to support Any CPU for both dotnet core and dotnet framework. The core dll will be able to pick the right loader at runtime

**Comment by billybooth** [comment]
@dianaqu, that is great news!  Does that imply that both loaders will be copied to output when it is appropriate?  Thanks so much for your work on this.

**Comment by dianaqu** [comment]
> @dianaqu, that is great news! Does that imply that both loaders will be copied to output when it is appropriate? Thanks so much for your work on this.

Yes! For dotnet core, we rely on dotnet core runtime build in ability and just add runtime folders to NuGet pacakge, then it will copy those folder structure to the output path and chose the right loader at runtime.
For dotnet frameowork, we copy both loader to output path under sub folder directory. And then we did extra implementation to the core dll to let it be able to pick loader from those sub folders. 
Right now all dlls will be copied to the output path, but they all live in different sub folders . Like x86 and x64. 

Does that serve the need for your product?

**Comment by billybooth** [comment]
> Does that serve the need for your product?

It absolutely does.  For dotnet framework, you may consider the `$(Platform)`, `$(PlatformTarget)`, and `$(Prefer32Bit)` conditions together to determine if only a single loader (x86 or x64) needs to be copied to output, but for our product, both are needed.

In any case, if a framework product targets x64 or x86 specifically, it's no trouble to distribute only the loader that is needed via  post-build step or a modification to the `.targets`.  The main thing that's so important is the ability to distribute both loaders (if necessary) and letting the core dll choose the appropriate loader at runtime.  If I were allowed to be greedy, I would prefer both the x64 and x86 loaders to be copied directly to output with different filenames (i.e.,`WebView2Loader.x86.dll` and `WebView2Loader.x64.dll` when both are needed and just `WebView2Loader.dll` when one is needed), rather than subfolders, but that is a _very_ small complaint indeed.

**Comment by dianaqu** [comment]
@billybooth May I ask why its important for you product to have loader in different names? We do have a backlog item on renaming the loader to be bit specific. But original it was because for dotnet, we can't support any cpu at runtime yet. I want to understand more on your needs so we can better plan our task base on priority.

**Comment by billybooth** [comment]
It's really not tremendously important.  I did see the non-dotnet backlog issue, which seems somewhat similarly motivated.  For me, it's only a matter of personal preference, since all of our dependencies (as I believe is typical with dotnet framework apps) currently exist in the single distributed output directory.  My thinking is that it would be ideal, when a framework application targets `x64`, `x86`, or `AnyCPU` (with `Prefer32Bit`), only a single loader dll (`WebView2Loader.dll`) is copied to the output path.  In the context of a dotnet framework application, the only circumstance where both loaders are needed, as I understand it, is when the application targets `AnyCPU` (without `Prefer32Bit`), and in that case it would be nice to see them both copied directly to the output with unique filenames rather than introducing a additional folders per architecture.  But again, it's really only an aesthetic preference.

**Comment by dianaqu** [comment]
@billybooth Thanks for the detailed explanation. I will bring it up in our next team meeting!

**Comment by champnic** [comment]
This is fixed and available in the next prerelease package, 0.9.628-prerelease. Thanks!

**Comment by billybooth** [comment]
We are now seeing the appropriate, per-architecture loaders copied into the output directories with the 0.9.628-prerelease, although we are still getting a `BadImageFormatException` when the platform is `AnyCPU` and `$(Prefer32Bit)` is checked.  Our expectation is that when the process is a 32-bit runtime process, the core should still be able to choose the appropriate (x86) loader.

#477 is obviously the same issue.  Thanks for your feedback on this.  Let me know if you'd like me to create a new issue to pursue this.

**Comment by champnic** [comment]
No need for a new issue. We're using #431 to track this (although we have lots of duplicate issues). We have a fix and it should be available in the next release. Thanks!

**Comment by AdmiralSnyder** [comment]
hey, i think the same issue occurs when building a vsix as AnyCPU - it only brings in the runtimes\win-x86\native folder with the web2loader.dll. - which is a problem if you want to build an extension for both VS2019 and 2022. can you confirm? should i create a new issue?
thanks,

Alex

**Comment by champnic** [comment]
@AdmiralSnyder If you could open a new issue I think that would be helpful. If you have a sample app the demonstrates the issue that would also be really helpful. Thanks!
