### ISSUE TITLE
Trying to open an empty popup window crashes WebView2 if an event handler is attached to NewWindowRequested

### ISSUE THREAD

**Issue by RichardSteele** [MicrosoftEdge/WebViewFeedback#293]
This is a follow-up to issue #134.
Make sure that a handler is attached to NewWindowRequested to create popup windows yourself and try to execute following code:
```
window.open();
```
What follows is a crash of WebView2.

[AB#27092950](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27092950)

**Comment by champnic** [comment]
Thanks for the follow-up @RichardSteele, I've opened this as a bug internally and we'll take a look. Thanks!

**Comment by champnic** [comment]
This should be fixed in Edge 86.0.613.0+. Thanks!

**Comment by RichardSteele** [comment]
The crash is gone but it still doesn't work as originally intended in #134. I've created another issue #409.
